name: gh-pages
on:
  push:
    branches: master

env:
  mcss_TAG: 374ec55a6610c1856e7374aea7dc1535ed8b64f8

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y xsltproc texlive ghostscript graphviz texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended flex bison
          git clone --depth 1 --branch Release_1_9_1 https://github.com/doxygen/doxygen.git
          cd doxygen && mkdir build && cd build
          cmake -G "Unix Makefiles" ..
          sudo make install

      - name: Fetch Python deps
        run: python3 -m pip install jinja2 Pygments docutils

      - name: Fetch m.css
        run: |
          cd ${GITHUB_WORKSPACE}
          git clone https://github.com/mosra/m.css.git
          cd m.css
          git checkout ${mcss_TAG}

      - name: Build docs
        run: |
          cd docs
          mkdir site
          python3 ${GITHUB_WORKSPACE}/m.css/documentation/doxygen.py conf.py

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: docs/site

  deploy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
